docker run -it -d \
  --label traefik.http.routers.jipson.rule=Host\(\`jipsonmicrocredit.phamasoft.com\`\) \
  --label traefik.http.routers.jipson.tls.certresolver=lets-encrypt \
  --label traefik.http.routers.jipson.tls=true \
  --label traefik.http.routers.jipson.service=jipson-credit-http \
  --label traefik.http.services.jipson-credit-http.loadbalancer.server.port=80 \
  --name jipsonmicrocredit \
  --network web \
  --restart always \
  --expose 80 \
  emasanga/mikoposoft:may13