docker run -it -d \
  --label traefik.http.routers.jpson.rule=Host\(\`jpsonmicrocredit.phamasoft.com\`\) \
  --label traefik.http.routers.jpson.tls.certresolver=lets-encrypt \
  --label traefik.http.routers.jpson.tls=true \
  --label traefik.http.routers.jpson.service=jpson-credit-http \
  --label traefik.http.services.jpson-credit-http.loadbalancer.server.port=80 \
  --name jpsonmicrocredit \
  --network web \
  --restart always \
  --expose 80 \
  emasanga/mikoposoft:may13